// Next.js-specific overlay on the base config — Doc 12 §3.
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import globals from 'globals';
import base from './base.js';

/** @type {import('eslint').Linter.Config[]} */
export default [
  ...base,
  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      globals: {
        ...globals.browser,
      },
    },
    plugins: {
      react,
      'react-hooks': reactHooks,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      'react/jsx-uses-react': 'off',
      'react/react-in-jsx-scope': 'off',
    },
  },
  {
    // Next.js App Router requires default exports for these framework-reserved files —
    // this is a documented exception to Doc 12 §1's named-exports rule, not a violation of it.
    files: [
      '**/app/**/page.tsx',
      '**/app/**/layout.tsx',
      '**/app/**/loading.tsx',
      '**/app/**/error.tsx',
      '**/app/**/global-error.tsx',
      '**/app/**/not-found.tsx',
      '**/app/**/route.ts',
      '**/middleware.ts',
      'next.config.*',
      'tailwind.config.*',
      'postcss.config.*',
      'vitest.config.*',
    ],
    rules: {
      'no-restricted-syntax': 'off',
    },
  },
  {
    // Auto-generated by `next dev`/`next build`, explicitly marked
    // "should not be edited" — its triple-slash references are how Next
    // itself writes this file, not a violation to fix.
    ignores: ['**/next-env.d.ts'],
  },
];
